//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPAIUEO.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPAIUEO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 イカ/乌贼◎
        ///かう/买う◎
        ///めさす/目指す②
        ///たたかう/戦う◎
        ///おく/置く置く②
        ///アイス/ice①
        ///きたい/期待期待
        ///ここ◎
        ///きこく/帰国
        ///ちかく/近く
        ///きかい/机械
        ///そこく/祖国
        ///しお/塩
        ///しあい/试合
        ///ちしき/知识
        ///かお/颜
        ///たいせつ/大切
        ///あいて/相手
        ///くつした/靴下
        ///てあし/手足
        ///きおく/记忆
        ///せかい/世界
        ///くけい/矩形
        ///あと/後
        ///てあて/手当て
        ///くう/食う
        ///あさい/浅い
        ///いたい/痛い
        ///くい/悔い
        ///きそ/基础
        ///とくい/得意
        ///いく/行く
        ///あす/明日
        ///とち/土地
        ///ココア/cocoa
        ///しき/四季
        ///とけい/时计
        ///けいき/景気
        ///あし/脚
        ///いと/意図
        ///こく/浓く
        ///うし/牛
        ///ちかう/誓う
        ///こえ/声
        ///こし/腰
        ///うち/内
        ///こい/鲤
        ///おす/推す
        ///つくえ/机
        ///すくう/救う
        ///きそく/规则
        ///きせき/奇迹
        ///おたく/お宅
        ///つかう/使う
        ///きく/闻く
        ///しかく/资格 的本地化字符串。
        /// </summary>
        internal static string danci1 {
            get {
                return ResourceManager.GetString("danci1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 あ行单词总结： 
        ///
        ///あ ア 
        ///● 雨（あめ）① 雨 
        ///● 飴（あめ）② 糖 
        ///● 挨拶（あいさつ）① 招呼 
        ///● 赤い（あかい）② 红的 
        ///● 青い（あおい）② 蓝的，绿的，苍白的 
        ///
        ///い イ 
        ///● 家（いえ）② 家 
        ///● 椅子（いし）○ 0 椅子 
        ///● 糸（いと）① 线，丝 
        ///● 犬（いぬ）② 狗 
        ///● 石（いし）② 石头 
        ///
        ///う ウ 
        ///● 牛（うし）② 牛 
        ///● 歌う（うたう）③ 唱歌 
        ///● 嬉しい（うれしい）③ 欢喜的，高兴的，喜悦的 
        ///● 海（うみ）① 海，大海 
        ///● 馬（うま）② 马 
        ///
        ///え エ 
        ///● 絵（え）① 画，图画 
        ///● 映画（えいが）○ 0 电影 
        ///● 遠足（えんそく）○ 0 远足，郊游，（徒步）旅游 
        ///● 演奏（えんそう）○ 0 演奏 
        ///● 演出（えんしゅつ）○ 0 演出，表演 
        ///
        ///お オ 
        ///● 思う（おもう）② 想，认为，打算 
        ///● 男（おとこ）③ 男子，男人 
        ///● 女（おんな）③ 女子，女人 
        ///● 起きる（おきる）② 起床，起来 
        ///● 温泉（おんせん）○ 0 温泉 
        ///
        ///绕口令练习： 
        ///あえい あおう あえいう [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string danci2 {
            get {
                return ResourceManager.GetString("danci2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
